{
 "title": "Perun-Watcher",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Watcher's running tasks",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perun_watcher_current_GetFileInfo",
     "legendFormat": "GetFileInfo"
    },
    {
     "expr": "perun_watcher_current_ListFiles",
     "legendFormat": "ListFiles"
    },
    {
     "expr": "perun_watcher_current_ListImages",
     "legendFormat": "ListImages"
    },
    {
     "expr": "perun_watcher_current_ListPrereleases",
     "legendFormat": "ListPrereleases"
    },
    {
     "expr": "perun_watcher_current_ListRepositories",
     "legendFormat": "ListRepositories"
    },
    {
     "expr": "perun_watcher_current_ListSnapshots",
     "legendFormat": "ListSnapshots"
    }
   ]
  },
  {
   "title": "Watcher's tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "perun_watcher_queued_tasks", "legendFormat": "Queued tasks" },
    { "expr": "perun_watcher_queue_size", "legendFormat": "Queue size" }
   ]
  },
  {
   "title": "Watcher's workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "perun_watcher_worker_busy", "legendFormat": "Busy" },
    { "expr": "perun_watcher_worker_idle", "legendFormat": "Idle" }
   ]
  }
 ]
}